### PR TITLE
Type matcher now return None when number of constructor arguments pat…

### LINKED ISSUE #20: Patterns for types with variadic constructor like Tuple
Right now when type is matched it is expected that number of provided patterns must be the same as number of arguments used for construction. This behavior is unexpected when discussing types constructed with variadic number of arguments. It could be possible to provide different case pattern for different number of arguments in constructor.

In example below three commented statements will be break by `InvalidPatternsNumber` exception.

```
<?php

declare(strict_types=1);

require_once __DIR__.'/../vendor/autoload.php';

use Scalp\Collection\Tuple;
use function Scalp\PatternMatching\match;
use function Scalp\PatternMatching\Type;
use function Scalp\PatternMatching\Any;
use function Scalp\println;

function tupleName(Tuple $tuple): string
{
    return match($tuple)
        ->case(Type(Tuple::class, Any()), function () { return 'Singleton'; })
        ->case(Type(Tuple::class, Any(), Any()), function () { return 'Pair'; })
        ->case(Type(Tuple::class, Any(), Any(), Any()), function () { return 'Triple'; })
        ->case(Type(Tuple::class), function () { return 'Other tuple'; })
        ->done();
}

//println(tupleName(new Tuple(1, 2)));
println(tupleName(new Tuple(1)));
//println(tupleName(new Tuple(1, 2, 3, 4)));
//println(tupleName(new Tuple(1, 2, 3)));
```

### PR DESCRIPTION
**Pull request by pawaclawczyk**
…terns does not match the number of arguments used for construction. This fix is related with matching against types with variadic number of arguments in constructor.

Fixes #20

### CODE REVIEW

File: tests/Scalp/PatternMatching/TypeTest.php [hunk 1]
```diff
@@ -100,13 +99,12 @@ public function it_returns_all_bound_values(): void
     }
 
     /** @test */
-    public function it_requires_patterns_for_all_constructor_arguments(): void
+    public function it_does_not_match_when_number_of_constructor_arguments_patterns_does_not_match_the_number_of_constructor_arguments(): void
```
Comment (lzakrzewski) [inline tests/Scalp/PatternMatching/TypeTest.php]: `it_does_not_match_when_number_of_constructor_arguments_patterns_does_not_match_the_number_of_constructor_arguments`
mumbo jumbo?

Comment (pawaclawczyk) [reply tests/Scalp/PatternMatching/TypeTest.php]: `it_does_not_match_if_number_of_arguments_patterns_is_different_than_number_of_used_arguments`?

The property is that you can provided patterns for each argument used to object construction and if you provided different number of patterns then number of arguments passed to the case class constructor then the matcher will not fit to the object at all.

Let me know if something is not clear.

**Review by lzakrzewski — APPROVED** [review]
